<?php

namespace NoInc\SimpleStorefrontBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCartByToken(string $token)
    {
        return $this->findOneBy(['token' => $token]);
    }

    public function getAll()
    {
        return $this->findAll();
    }
}

