<?php

namespace NoInc\SimpleStorefrontBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIngredientByName(string $name)
    {
        return $this->findOneBy(['name' => $name]);
    }

    public function getAll()
    {
        return $this->findAll();
    }
}
