<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-05-02 04:02:02.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace NoInc\SimpleStorefrontBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * NoInc\SimpleStorefrontBundle\Entity\CartItem
 *
 * @ORM\Entity(repositoryClass="NoInc\SimpleStorefrontBundle\Repository\CartItemRepository")
 * @ORM\Table(name="cart_item", indexes={@ORM\Index(name="fk_cart_item_cart_idx", columns={"cart_id"}), @ORM\Index(name="fk_cart_item_product_idx", columns={"product_id"})})
 */
class CartItem
{
    /**
     * ID of the Cart's item
     *
     * @ORM\Id
     * @ORM\Column(type="integer", nullable=false)
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * ID of the Recipe associated with the Recipe Igredient
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $cart_id;

    /**
     * ID of the Product associated with the cart item
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $product_id;

    /**
     * @ORM\ManyToOne(targetEntity="Cart", inversedBy="cartItems")
     * @ORM\JoinColumn(name="cart_id", referencedColumnName="id", nullable=false)
     */
    protected $cart;

    /**
     * @ORM\OneToOne(targetEntity="Product", mappedBy="cartItem")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id", nullable=false)
     */
    protected $product;

    public function __construct()
    {
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of product_id.
     *
     * @param integer $product_id
     * @return \NoInc\SimpleStorefrontBundle\Entity\CartItem
     */
    public function setProductId($product_id)
    {
        $this->product_id = $product_id;

        return $this;
    }

    /**
     * Get the value of product_id.
     *
     * @return integer
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Set the value of cart_id.
     *
     * @param integer $cart_id
     * @return \NoInc\SimpleStorefrontBundle\Entity\CartItem
     */
    public function setCartId($cart_id)
    {
        $this->cart_id = $cart_id;

        return $this;
    }

    /**
     * Get the value of cart_id.
     *
     * @return integer
     */
    public function getCartId()
    {
        return $this->cart_id;
    }

    /**
     * Set Recipe entity (many to one).
     *
     * @param \NoInc\SimpleStorefrontBundle\Entity\Product $product
     * @return \NoInc\SimpleStorefrontBundle\Entity\CartItem
     */
    public function setProduct(Product $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get Recipe entity (many to one).
     *
     * @return \NoInc\SimpleStorefrontBundle\Entity\Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * Set Cart entity (many to one).
     *
     * @param \NoInc\SimpleStorefrontBundle\Entity\Cart $cart
     * @return \NoInc\SimpleStorefrontBundle\Entity\CartItem
     */
    public function setCart(Cart $cart = null)
    {
        $this->cart = $cart;

        return $this;
    }

    /**
     * Get Cart entity (many to one).
     *
     * @return \NoInc\SimpleStorefrontBundle\Entity\Cart
     */
    public function getCart()
    {
        return $this->cart;
    }

    public function __sleep()
    {
        return array('id', 'product_id', 'cart_id');
    }
}

